### ISSUE TITLE
User login UI flow can be improved

### ISSUE THREAD

**Issue by KartikWatts** [VenusTokyo/QuikNote#1]
I was just going through the app, nice stuff. I believe the login UI flow could be improved.

1. If a user is not logged in, and directly comes at route: `/`, the intermediate dashboard is displayed before navigating to the login screen, also triggering the APIs only to end up with `Unauthorized` errors:
![image](https://github.com/user-attachments/assets/31727bde-ba09-45dc-940a-7ad242bb6ea0)

2. An already logged-in User can visit the route `/login` with no proper UI to display if they are already logged in.

Proposed Solution:
Local storage item **token** could be utilized to smoothly render the UI without additional overhead, i.e. logged-out user could be navigated to `/login` and the logged-in user could be navigated to the `/` dashboard.

Would love to hear your thoughts, regards.

**Comment by VenusTokyo** [comment]
Hi Kartik,

Thank you for bringing this to my attention and for the detailed description of the issue.

Your proposed solution to use the local storage item token for smoother UI rendering sounds great. I would appreciate it if you could create a pull request with the necessary changes to resolve this issue. This would allow me to review and integrate your solution into the project.

Looking forward to your contribution! ✨

**Comment by KartikWatts** [comment]
Hi @VenusTokyo, sure that would be great. Will raise the PR by tomorrow. Regards.

**Comment by KartikWatts** [comment]
@VenusTokyo Raised the PR, let me know your thoughts, after some consideration, I thought to implement HOCs to ensure we only render the component when the auth state is satisfied to ensure smooth behavior.

**Comment by VenusTokyo** [comment]
@KartikWatts Good work, PR Merged 😃
