### ISSUE TITLE
Issue with Vercel route rewrite configuration in frontend

### ISSUE THREAD

**Issue by KartikWatts** [VenusTokyo/QuikNote#3]
I have come across an issue related to Vercel configuration FE project, the routes are not being properly configured when any route other than the index is directly visited.

Reproduce:
Visit: https://quiknote-venustokyo.vercel.app/login

Result:
![Screenshot_20240438](https://github.com/user-attachments/assets/b4c8f567-b7f7-4fe6-97db-f7e251811842)

Expectation:
The route should be properly configured.

Solution:
I could get some references from similar discussion wrt Vercel: https://stackoverflow.com/questions/64815012/why-does-react-router-not-works-at-vercel, https://vercel.com/docs/projects/project-configuration#project/rewrites

Raising a PR already :)

**Comment by VenusTokyo** [comment]
Thankyou for fixing this issue had been stuck on it for days. Keep up the good work ✨
